name: Build RE4 Save Redirect Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Setup Detours
      run: |
        # Download pre-built Detours library using PowerShell
        Invoke-WebRequest -Uri "https://github.com/microsoft/detours/releases/download/v4.0.1/detours-4.0.1-x86.zip" -OutFile detours.zip
        7z x detours.zip -odetours
        # Copy required files
        Copy-Item "detours\lib.X86\detours.lib" .
        Copy-Item "detours\include\detours.h" .
        Copy-Item "detours\include\detver.h" .
      shell: powershell

    - name: Build with MSVC
      run: |
        # Build the DLL with dependencies using Visual Studio compiler
        cl /LD /Fe:RE4SaveRedirect.dll dllmain.cpp /link detours.lib shlwapi.lib
      shell: cmd
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        path: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md
          
  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md