name: Build RE4 Save Redirect Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Setup Detours
      run: |
        # Download Detours source
        git clone https://github.com/microsoft/detours.git
        cd detours
        # Checkout a stable version
        git checkout v4.0.1
        
        # Build Detours using available tools
        cd src
        nmake
        cd ..

        # Copy required files
        Copy-Item "lib.X86\detours.lib" .
        Copy-Item "include\detours.h" .
        Copy-Item "include\detver.h" .
      shell: powershell

    - name: Verify Detours files
      run: |
        # Check if required files exist
        if (Test-Path "detours.h") {
          Write-Host "detours.h found"
        } else {
          Write-Host "ERROR: detours.h not found" -ForegroundColor Red
        }
        if (Test-Path "detours.lib") {
          Write-Host "detours.lib found"
        } else {
          Write-Host "ERROR: detours.lib not found" -ForegroundColor Red
        }
      shell: powershell

    - name: Build with MSVC
      run: |
        REM Build the DLL with dependencies using Visual Studio compiler
        cl /LD /I. /Fe:RE4SaveRedirect.dll dllmain.cpp /link detours.lib shlwapi.lib
      shell: cmd
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        path: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md
          
  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md