name: Build RE4 Save Redirect Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW-w64
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH
      shell: powershell

    - name: Prepare build environment
      run: |
        # Copy our stub header for compilation
        Copy-Item "detours_stub.h" "detours.h"
        
        # Create a simple implementation for compilation using PowerShell to avoid encoding issues
        Set-Content -Path "detours_impl.cpp" -Value @'
        #include "detours.h"
        
        // Undefine macros to allow function definitions
        #undef DetourTransactionBegin
        #undef DetourTransactionCommit
        #undef DetourUpdateThread
        #undef DetourAttach
        #undef DetourDetach
        
        void DetourTransactionBegin() {}
        void DetourTransactionCommit() {}
        void DetourUpdateThread(void* hThread) {}
        void DetourAttach(PPVOID ppPointer, PVOID pDetour) {}
        void DetourDetach(PPVOID ppPointer, PVOID pDetour) {}
        '@
        
        # Compile the stub implementation
        g++ -c detours_impl.cpp -o detours_impl.o
      shell: powershell

    - name: Build with MinGW
      run: |
        # Build the DLL with dependencies
        g++ -shared -O2 -Wall -Wextra -D_WIN32_WINNT=0x0501 -D_USE_DETOURS_STUB -DUNICODE -D_UNICODE dllmain.cpp detours_impl.o -o RE4SaveRedirect.dll -lshlwapi
      shell: powershell
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        path: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md
          
  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: RE4SaveRedirect-Build
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RE4SaveRedirect.dll
          re4_save_redirect.ini
          README.md